FROM projectfurnace/deploy-base:latest

RUN pip3 install awscli

WORKDIR /app

ARG NPM_TOKEN  
#COPY .npmrc .npmrc 

COPY package*.json ./

RUN npm install

#RUN rm -f .npmrc

COPY . .

CMD /app/deploy_aws.sh
