version: "3"

services:
  deploy:
    volumes:
      - ./test/fixtures/config/azure:/furnace/stack
      - ./test/fixtures/templates:/furnace/templates
    env_file:
      - env/azure.env
    build:
      context: .
      # args:


